### PR TITLE
terraform dshield honeypot deployment

### PR DESCRIPTION
**Pull request by dlee35**
This code completes the following items:
- deploys `X` amount of Ubuntu 20.04 t2.micro EC2 instances based upon the value of `honeypot_nodes` (default: `1`) into a predefined region (from the `variables.tf` file) into a VPC and Security Group with an associated internet gateway  
- builds the dshield.ini file from template using declared variables (or prompted for an API key, email, and DShield UserId if not stored in `*.tfvars` file locally)  
- builds the dshield.sslca file using the same method  
- changes the SSH port in sshd_config to the default (12222 but can be defined in `variables.tf`) and restarts the service  
- runs the install scripts to complete the unattended installation  
- adds an output to cowrie to log to `cowrie.json` if `output_logging` is set to `true`  
- appends a logrotate policy to `/etc/logrotate.d/dshield` for `cowrie.json` to manage file growth  
- reboots upon completion

### CODE REVIEW

**Comment by dlee35** [comment]
I'm working on the deployment documentation now. Happy to answer any questions if necessary. Thanks!

**Comment by dlee35** [comment]
Added `terraform` deployment instructions

**Review by dlee35 — COMMENTED** [review]
this was actually a typo correction to `nohoneyports` and an addition to `nofwlogging`

**Review by jullrich — APPROVED** [review]

**Review by jullrich — APPROVED** [review]

**Review by jullrich — APPROVED** [review]

**Review by jullrich — APPROVED** [review]
I may add a variable in dshield.ini shortly to enable more verbose local logging.

**Review by jullrich — APPROVED** [review]

**Review by jullrich — APPROVED** [review]

**Pull request merged**
