### PR TITLE
ISC Agent fixes

### PR DESCRIPTION
**Pull request by DeemOnSecurity**
Working on fixing the ISC Agent as it's currently blocking automated pull requests. Originally thought this was only an issue with the working directory specified in the docker action, but there are some deeper rooted threads I'm pulling at to get this agent working.

### CODE REVIEW

**Comment by DeemOnSecurity** [comment]
Working directory and image path are fixed, so code scan is working as expected. Now we have some other bugs with isc-agent. Debugging now.

Most recent bug:
```
************* Module sans-isc-agent.main
[119](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:120)
main.py:1:0: E0401: Unable to import 'plugins.tcp' (import-error)
[120](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:121)

[121](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:122)
-----------------------------------
[122](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:123)
Your code has been rated at 9.63/10
```

**Comment by DeemOnSecurity** [comment]
> Working directory and image path are fixed, so code scan is working as expected. Now we have some other bugs with isc-agent. Debugging now.
> 
> Most recent bug:
> 
> ```
> ************* Module sans-isc-agent.main
> [119](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:120)
> main.py:1:0: E0401: Unable to import 'plugins.tcp' (import-error)
> [120](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:121)
> 
> [121](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:122)
> -----------------------------------
> [122](https://github.com/DShield-ISC/dshield/actions/runs/3997487506/jobs/6858894088#step:3:123)
> Your code has been rated at 9.63/10
> ```

It appears that `isc-agent/plugins/tcp` is not being recognized as a Python module or is not being copied properly to the docker container

**Comment by DeemOnSecurity** [comment]
Attempted to modify init hook to see if it was a plugin recognition issue and no change was noticed in behavior. Me thinks this is a Docker configuration related issue. Investigating.

**Review by jullrich — APPROVED** [review]

**Comment by jullrich** [comment]
not that "isc-agent" is meant to be a replacement for the current web.py.

**Pull request merged**
